---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: httpbin
  namespace: flux-system
spec:
  interval: 1m0s
  type: oci
  url: oci://gelding36358acr.azurecr.io/helm
  passCredentials: true
  secretRef:
    name: https-credentials
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: httpbin
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: apps
  chart:
    spec:
      chart: httpbin
      version: '1.0.0'
      sourceRef:
        kind: HelmRepository
        name: httpbin
        namespace: flux-system
      interval: 1m